name: First Workflow 

on:
  push:
    branches:
      - main
  workflow_dispatch:
     
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print a welcome message
      run: echo "welcome to our first Github actions workflow!"
      
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: List repository files
      run: ls -la
